import Foundation

public struct ScaffoldGenerator {
    public let repoRoot: URL
    private let fileManager: FileManager

    public init(repoRoot: URL, fileManager: FileManager = .default) {
        self.repoRoot = repoRoot
        self.fileManager = fileManager
    }

    @discardableResult
    public func scaffold(
        slice: SliceDefinition,
        report: PortabilityReport,
        comparison: ComparisonReport,
        targets: [FrameworkTarget]
    ) throws -> HeliosSliceManifest {
        let manifest = HeliosSliceManifest(
            slice: slice,
            tabs: try extractTabs(relativePath: "Packages/OsaurusCore/Models/Configuration/ManagementTab.swift"),
            serviceInterfaces: slice.serviceInterfaces,
            sourcePaths: slice.sourcePaths,
            todoMarkers: HeliosPorterSupport.serverTodoMarkers
        )

        let sharedDir = HeliosPorterSupport.sharedDirectory(repoRoot: repoRoot)
        try HeliosPorterSupport.ensureDirectory(sharedDir, fileManager: fileManager)

        let manifestURL = sharedDir.appendingPathComponent("\(slice.slug).slice.json")
        let data = try HeliosPorterSupport.makeEncoder().encode(manifest)
        try HeliosPorterSupport.write(data, to: manifestURL, fileManager: fileManager)

        for target in targets {
            try scaffoldTarget(
                target,
                manifest: manifest,
                comparison: comparison
            )
        }

        return manifest
    }

    private func extractTabs(relativePath: String) throws -> [String] {
        let source = try HeliosPorterSupport.readSource(at: relativePath, repoRoot: repoRoot)
        return HeliosPorterSupport.firstMatches(pattern: #"^\s*case\s+([a-zA-Z_][a-zA-Z0-9_]*)"#, in: source, limit: 64)
    }

    private func scaffoldTarget(
        _ target: FrameworkTarget,
        manifest: HeliosSliceManifest,
        comparison: ComparisonReport
    ) throws {
        let root: URL
        let packageName: String
        let executableName: String

        switch target {
        case .swiftcrossui:
            root = repoRoot.appendingPathComponent("Helios/swiftcrossui", isDirectory: true)
            packageName = "HeliosSwiftCrossUI"
            executableName = "HeliosSwiftCrossUIApp"
        case .shaft:
            root = repoRoot.appendingPathComponent("Helios/shaft", isDirectory: true)
            packageName = "HeliosShaft"
            executableName = "HeliosShaftApp"
        }

        try HeliosPorterSupport.ensureDirectory(root, fileManager: fileManager)
        try HeliosPorterSupport.write(packageManifest(packageName: packageName, executableName: executableName), to: root.appendingPathComponent("Package.swift"), fileManager: fileManager)
        try HeliosPorterSupport.write(readme(target: target, comparison: comparison), to: root.appendingPathComponent("README.md"), fileManager: fileManager)

        let sources = root.appendingPathComponent("Sources/\(executableName)", isDirectory: true)
        try HeliosPorterSupport.ensureDirectory(sources, fileManager: fileManager)
        try HeliosPorterSupport.write(mainFile(target: target, executableName: executableName), to: sources.appendingPathComponent("main.swift"), fileManager: fileManager)
        try HeliosPorterSupport.write(platformServicesFile(), to: sources.appendingPathComponent("PlatformServices.swift"), fileManager: fileManager)
        try HeliosPorterSupport.write(
            managementSettingsSliceFile(
                target: target,
                executableName: executableName,
                manifest: manifest
            ),
            to: sources.appendingPathComponent("ManagementSettingsSlice.swift"),
            fileManager: fileManager
        )
    }

    private func packageManifest(packageName: String, executableName: String) -> String {
        """
        // swift-tools-version: 6.2
        import PackageDescription

        let package = Package(
            name: "\(packageName)",
            products: [
                .executable(name: "\(packageName.lowercased())", targets: ["\(executableName)"])
            ],
            targets: [
                .executableTarget(name: "\(executableName)")
            ]
        )
        """
    }

    private func readme(target: FrameworkTarget, comparison: ComparisonReport) -> String {
        """
        # \(target.rawValue) Helios Slice Scaffold

        Generated by `helios-porter scaffold --slice management_settings --targets swiftcrossui,shaft`.

        - Comparison winner: `\(comparison.recommendedTarget.rawValue)`
        - Shared manifest: `../shared/management-settings.slice.json`
        - Shared service surface: `ClipboardService`, `ExternalLinkService`, `ServerControlService`, `SettingsNavigationService`

        This scaffold is intentionally lightweight. It keeps the first `Management/Settings` slice isolated while the Helios Windows app is still deciding how much of Osaurus should remain shared and how much should be rewritten natively.
        """
    }

    private func mainFile(target: FrameworkTarget, executableName: String) -> String {
        let title = target == .swiftcrossui ? "SwiftCrossUI" : "Shaft"
        return """
        import Foundation

        #if canImport(\(title))
        import \(title)
        #endif

        @main
        struct \(executableName) {
            static func main() {
                #if canImport(\(title))
                print("Wire the \(title) runtime here and point it at ../shared/management-settings.slice.json.")
                #else
                print("The \(title) dependency is not installed yet. This scaffold stays compile-safe while Helios settles the Windows runtime.")
                #endif
            }
        }
        """
    }

    private func platformServicesFile() -> String {
        """
        import Foundation

        protocol ClipboardService {
            func copy(_ text: String)
        }

        protocol ExternalLinkService {
            func open(_ url: String)
        }

        protocol ServerControlService {
            func currentStatus() -> String
            func localServerURL() -> String
            func refreshStatus()
        }

        protocol SettingsNavigationService {
            func showServerOverview()
            func showAPIReference()
        }

        struct PlatformServices {
            let clipboard: ClipboardService
            let links: ExternalLinkService
            let server: ServerControlService
            let navigation: SettingsNavigationService
        }

        struct PlaceholderClipboardService: ClipboardService {
            func copy(_ text: String) {}
        }

        struct PlaceholderExternalLinkService: ExternalLinkService {
            func open(_ url: String) {}
        }

        struct PlaceholderServerControlService: ServerControlService {
            func currentStatus() -> String { "Unknown" }
            func localServerURL() -> String { "http://127.0.0.1:1337" }
            func refreshStatus() {}
        }

        struct PlaceholderSettingsNavigationService: SettingsNavigationService {
            func showServerOverview() {}
            func showAPIReference() {}
        }

        extension PlatformServices {
            static let placeholder = PlatformServices(
                clipboard: PlaceholderClipboardService(),
                links: PlaceholderExternalLinkService(),
                server: PlaceholderServerControlService(),
                navigation: PlaceholderSettingsNavigationService()
            )
        }
        """
    }

    private func managementSettingsSliceFile(
        target: FrameworkTarget,
        executableName: String,
        manifest: HeliosSliceManifest
    ) -> String {
        let tabs = manifest.tabs.map { "    case \($0)" }.joined(separator: "\n")
        let todoMarkers = manifest.todoMarkers.map { "// \($0)" }.joined(separator: "\n")
        let frameworkName = target == .swiftcrossui ? "SwiftCrossUI" : "Shaft"
        let rootType = target == .swiftcrossui ? "ManagementSettingsRootView" : "ManagementSettingsRootScreen"

        return """
        import Foundation

        let heliosSharedManifestPath = "../../shared/management-settings.slice.json"

        enum HeliosManagementTab: String, CaseIterable {
        \(tabs)
        }

        struct HeliosServerReadAction {
            let title: String
            let perform: () -> Void
        }

        struct HeliosServerOverviewModel {
            let status: String
            let localURL: String
            let readActions: [HeliosServerReadAction]
        }

        let heliosServerOverview = HeliosServerOverviewModel(
            status: PlatformServices.placeholder.server.currentStatus(),
            localURL: PlatformServices.placeholder.server.localServerURL(),
            readActions: [
                HeliosServerReadAction(title: "Copy Local URL") {
                    PlatformServices.placeholder.clipboard.copy(PlatformServices.placeholder.server.localServerURL())
                },
                HeliosServerReadAction(title: "Open Documentation") {
                    PlatformServices.placeholder.links.open("https://docs.osaurus.ai/")
                },
                HeliosServerReadAction(title: "Open Discord") {
                    PlatformServices.placeholder.links.open("https://discord.gg/dinoki")
                },
                HeliosServerReadAction(title: "Show API Reference") {
                    PlatformServices.placeholder.navigation.showAPIReference()
                },
            ]
        )

        \(todoMarkers)

        #if canImport(\(frameworkName))
        import \(frameworkName)

        struct \(rootType) {
            let services: PlatformServices = .placeholder
            let tabs = HeliosManagementTab.allCases

            // This is a framework-shaped bootstrap rather than a finished implementation.
            // It preserves the Management/Settings information architecture while Helios decides
            // how much of the final Windows shell should be owned by \(frameworkName).
        }
        #endif
        """
    }
}
